CaelumEstoque/Models/CategoriaDoProduto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class CategoriaDoProduto
    {
        public int Id { get; set; }

        public String Nome { get; set; }

        public String Descricao { get; set; }
    }
}

CaelumEstoque/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class Produto
    {
        public int Id { get; set; }

        [StringLength(20)]
        public String Nome { get; set; }

        public float Preco { get; set; }

        public CategoriaDoProduto Categoria { get; set; }

        public int? CategoriaId { get; set; }

        public String Descricao { get; set; }

        public int Quantidade { get; set; }
    }
}

CaelumEstoque/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaelumEstoque.Models
{
    public class Usuario
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Senha { get; set; }
    }
}

CaelumEstoque/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaelumEstoque.DAO;
using CaelumEstoque.Models;
namespace CaelumEstoque.Controllers
{
    public class CategoriaController : Controller
    {
        //
        // GET: /Produto/

        public ActionResult Index()
        {
            CategoriasDAO dao = new CategoriasDAO();
            IList<CategoriaDoProduto> categorias = dao.Lista();
            ViewBag.Categorias = categorias;
            return View();
        }

        public ActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Adiciona(CategoriaDoProduto categoria)
        {
            CategoriasDAO dao = new CategoriasDAO();
            dao.Adiciona(categoria);
            return RedirectToAction("Index");
        }
    }
}

CaelumEstoque/Controllers/ContadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class ContadorController : Controller
    {
        // GET: Contador
        public ActionResult Index()
        {
            object contadorSession = Session["contador"];
            int contador = Convert.ToInt32(contadorSession);
            contador++;
            Session["contador"] = contador;
            return View(contador);
        }
    }
}

CaelumEstoque/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CaelumEstoque/Controllers/LoginController.cs
using CaelumEstoque.DAO;
using CaelumEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaelumEstoque.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autentica(String login, String senha)
        {
            UsuariosDAO dao = new UsuariosDAO();
            Usuario usuario = dao.Busca(login, senha);
            if (usuario != null)
            {
                Session["usuarioLogado"] = usuario;
                return RedirectToAction("Index", "Produto");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CaelumEstoque/Controllers/ProdutoController.cs
using CaelumEstoque.DAO;
using CaelumEstoque.Filtros;
using CaelumEstoque.Models;
using System.Collections.Generic;
using System.Web.Mvc;
namespace CaelumEstoque.Controllers
{
    public class ProdutoController : Controller
    {
        //
        // GET: /Produto/

        [Route("produtos", Name = "ListaProdutos")]
        [AutorizacaoFilter]
        public ActionResult Index()
        {
            ProdutosDAO dao = new ProdutosDAO();
            var produtos = dao.Lista();
            return View(produtos);
        }

        public ActionResult Form()
        {
            ViewBag.Produto = new Produto();
            CategoriasDAO dao = new CategoriasDAO();
            IList<CategoriaDoProduto> categorias = dao.Lista();
            ViewBag.Categorias = categorias;
            return View(categorias);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adiciona(Produto produto)
        {
            int idDaInformatica = 1;
            if (produto.CategoriaId.Equals(idDaInformatica) && produto.Preco < 100)
            {
                ModelState.AddModelError("produto.InformaticaComPrecoInvalido", "Produtos da categoria informática devem ter preço maior do que 100");
            }
            if (ModelState.IsValid)
            {
                ProdutosDAO dao = new ProdutosDAO();
                dao.Adiciona(produto);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Produto = produto;
                CategoriasDAO categoriasDAO = new CategoriasDAO();
                ViewBag.Categorias = categoriasDAO.Lista();
                return View("Form");
            }
        }

        [Route("produtos/{id}", Name = "VisualizaProduto")]
        public ActionResult Visualiza(int id)
        {
            ProdutosDAO dao = new ProdutosDAO();
            Produto produto = dao.BuscaPorId(id);
            ViewBag.Produto = produto;
            return View();
        }

        public ActionResult DecrementaQtd(int id)
        {
            ProdutosDAO dao = new ProdutosDAO();
            Produto produto = dao.BuscaPorId(id);
            produto.Quantidade--;
            dao.Atualiza(produto);
            return Json(produto);
        }
    }
}

CaelumEstoque/Views/Categoria/Form.cshtml
<form action="/Categoria/Adiciona" method="post">
    <label for="nome">Nome:</label>
    <input name="categoria.Nome" id="nome" class="form-control" />

    <label for="descricao">Descrição:</label>
    <input name="categoria.Descricao" id="descricao" class="form form-control" />

    <input type="submit" value="Cadastrar" />
</form>

CaelumEstoque/Views/Categoria/Index.cshtml
<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome da Categoria</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var categoria in ViewBag.Categorias)
        {
            <tr>
                <td>@categoria.Id</td>
                <td>@categoria.Nome</td>
            </tr>
        }
    </tbody>
</table>

CaelumEstoque/Views/Contador/Index.cshtml
Contador atual:@Model

CaelumEstoque/Views/Home/Index.cshtml
<h1>Página Inicial da aplicação</h1>

CaelumEstoque/Views/Login/Index.cshtml
<form action="/Login/Autentica" method="post"> 
    <label for="login">Login:</label>
    <input name="login" id="login" class="form-control" />

    <label for="senha">Senha:</label>
    <input name="senha" id="senha" class="form-control" type="password" />

    <input type="submit" value="Logar" />
</form>

CaelumEstoque/Views/Produto/Form.cshtml
<form action="/Produto/Adiciona" method="post">
    @Html.AntiForgeryToken();
    @Html.ValidationMessage("produto.InformaticaComPrecoInvalido")

    <label for="nome">Nome:</label>
    <input id="nome" name="produto.Nome" value="@ViewBag.Produto.Nome" class="form-control" />
    @Html.ValidationMessage("produto.Nome")

    <label for="preco">Preço:</label>
    <input id="preco" name="produto.Preco" value="@ViewBag.Produto.Preco" class="form-control" />
    @Html.ValidationMessage("produto.Preco")

    <label for="quantidade">Quantidade:</label>
    <input id="quantidade" name="produto.Quantidade" value="@ViewBag.Produto.Quantidade" class="form-control" />
    @Html.ValidationMessage("produto.Quantidade")

    <label for="descricao">Descrição:</label>
    <input id="descricao" name="produto.Descricao" value="@ViewBag.Produto.Descricao" class="form-control" />
    @Html.ValidationMessage("produto.Descricao")

    <label for="categoria">Categoria:</label>
    <select id="categoria" name="produto.CategoriaId">
        @foreach (var categoria in ViewBag.Categorias)
        {
            <option value="@categoria.Id" selected="@categoria.Id.Equals(ViewBag.Produto.CategoriaId)">
                @categoria.Nome
            </option>
        }
    </select>
    @Html.ValidationMessage("produto.CategoriaId")

    <input type="submit" value="Cadastrar" />
</form>

CaelumEstoque/Views/Produto/Index.cshtml
@model IList<CaelumEstoque.Models.Produto>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var produto in Model)
        {
            <tr>
                <td>@produto.Id</td>
                <td>@produto.Nome</td>
                <td id="quantidade@(produto.Id)">@produto.Quantidade</td>
                <td><a href="#" onclick="decrementa(@produto.Id)">Decrementar</a></td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">

  function decrementa(produtoId){
    var url = "@Url.Action("DecrementaQtd", "Produto")";
    var params = {id : produtoId};
    $.post(url, params, atualiza);
  }

  function atualiza(resposta){
    var elemento = $("#quantidade" + resposta.Id);
    elemento.html(resposta.Quantidade);
  }
</script>

CaelumEstoque/Views/Produto/Visualiza.cshtml
<body>
    Id: @ViewBag.Produto.Id<br />
    Nome: @ViewBag.Produto.Nome<br />
    Quantidade: @ViewBag.Produto.Quantidade<br />
    Preço: @ViewBag.Produto.Preco<br />
    Descricao: @ViewBag.Produto.Descricao<br />
    Categoria: @ViewBag.Produto.Categoria.Nome<br />

    @Html.RouteLink("Voltar para a lista", "ListaProdutos")
</body>

CaelumEstoque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/Content/Css/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Css/Site.css" />
</head>
<body>
    <div class="container">
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
                <li>@Html.ActionLink("Categorias", "Index", "Categoria")</li>
                <li>@Html.ActionLink("Usuários", "Index", "Usuario")</li>
            </ul>
            <h3 class="muted-text">Caelum Estoque</h3>
        </div>
        <div id="conteudo">
            @RenderBody()
        </div>
    </div>
</body>
</html>